### ISSUE TITLE
full_path error, book is prohibited to download via web browser

### ISSUE THREAD

**Issue by Kuan-Lun** [NomadThanatos/readmoo-dl#13]
您好

我發現當指定[特定書本](https://readmoo.com/book/210092343000101)時，程式會無法執行。

    正在取得檔案路徑...
    DevTools listening on ws://127.0.0.1:65484/devtools/browser/09c82fb7-a30c-48e1-a3b3-8b7bbc9fd601
    [24988:19824:1113/184907.200:ERROR:fallback_task_provider.cc(124)] Every renderer should have at least one task provided by a primary task provider. If a "Renderer" fallback task is shown, it is a bug. If you have repro steps, please file a new bug and tag it as a dependency of crbug.com/739782.
    [24988:19824:1113/184908.527:ERROR:device_event_log_impl.cc(215)] [18:49:08.527] USB: usb_device_handle_win.cc:1048 Failed to read descriptor from node connection: 連結到系統的某個裝置失去作用。 (0x1F)
    [24988:19824:1113/184924.284:ERROR:fallback_task_provider.cc(124)] Every renderer should have at least one task provided by a primary task provider. If a "Renderer" fallback task is shown, it is a bug. If you have repro steps, please file a new bug and tag it as a dependency of crbug.com/739782.
    [24988:19824:1113/184925.962:ERROR:fallback_task_provider.cc(124)] Every renderer should have at least one task provided by a primary task provider. If a "Renderer" fallback task is shown, it is a bug. If you have repro steps, please file a new bug and tag it as a dependency of crbug.com/739782.
    成功
    正在取得 META-INF/container.xml...D:/Program Files/readmoo-dl-master/lib/readmoo_dl/downloader.rb:108:in `full_path': undefined method `+' for nil:NilClass (NoMethodError)
    
          base + path
               ^
            from D:/Program Files/readmoo-dl-master/lib/readmoo_dl/downloader.rb:49:in `fetch_container_file'
            from D:/Program Files/readmoo-dl-master/lib/readmoo_dl/downloader.rb:25:in `block in download'
          from D:/Program Files/readmoo-dl-master/lib/readmoo_dl/downloader.rb:38:in `job'
          from D:/Program Files/readmoo-dl-master/lib/readmoo_dl/downloader.rb:25:in `download'
          from main.rb:19:in `<main>'

**Comment by NomadThanatos** [comment]
I think this is due to `出版社不提供本書網頁試／閱讀，購買前／後請使用 App/mooInk 試／閱讀。`

I also have several books purchased cannot be downloaded via this program, most of them are published via 台灣角川.

So I just blacklist 台灣角川 on Readmoo, you can try to purchase them via Kobo and use https://github.com/subdavis/kobo-book-downloader

**Comment by NomadThanatos** [comment]
This program mimic reading the comics via browser, so if publisher bans you reading via browser, this program cannot work.

One improvement here is better error description.

**Comment by Ramzh** [comment]
@NomadThanatos I have this: https://readmoo.com/book/210263843000101

It does have a trial reading but I still the get same error shown here:

```[Running] ruby "c:\Users\z\Desktop\readmoo-dl-master\main.rb"
c:/Users/z/Desktop/readmoo-dl-master/lib/readmoo_dl/downloader.rb:108:in `full_path': undefined method `+' for nil:NilClass (NoMethodError)

      base + path
           ^
	from c:/Users/z/Desktop/readmoo-dl-master/lib/readmoo_dl/downloader.rb:49:in `fetch_container_file'
	from c:/Users/z/Desktop/readmoo-dl-master/lib/readmoo_dl/downloader.rb:25:in `block in download'
	from c:/Users/z/Desktop/readmoo-dl-master/lib/readmoo_dl/downloader.rb:38:in `job'
	from c:/Users/z/Desktop/readmoo-dl-master/lib/readmoo_dl/downloader.rb:25:in `download'
	from c:/Users/z/Desktop/readmoo-dl-master/main.rb:19:in `<main>'
正在取得檔案路徑...成功
正在取得 META-INF/container.xml...```

**Comment by PeepYXB** [comment]
> @NomadThanatos I have this: https://readmoo.com/book/210263843000101
> 
> It does have a trial reading but I still the get same error shown here:
> 
> ```
> c:/Users/z/Desktop/readmoo-dl-master/lib/readmoo_dl/downloader.rb:108:in `full_path': undefined method `+' for nil:NilClass (NoMethodError)
> 
>       base + path
>            ^
> 	from c:/Users/z/Desktop/readmoo-dl-master/lib/readmoo_dl/downloader.rb:49:in `fetch_container_file'
> 	from c:/Users/z/Desktop/readmoo-dl-master/lib/readmoo_dl/downloader.rb:25:in `block in download'
> 	from c:/Users/z/Desktop/readmoo-dl-master/lib/readmoo_dl/downloader.rb:38:in `job'
> 	from c:/Users/z/Desktop/readmoo-dl-master/lib/readmoo_dl/downloader.rb:25:in `download'
> 	from c:/Users/z/Desktop/readmoo-dl-master/main.rb:19:in `<main>'
> 正在取得檔案路徑...成功
> 正在取得 META-INF/container.xml...```
> ```

请问你解决了吗？我也出现了相似的问题
```
(base) yan@MacBook-Air readmoo-dl-master % bundle exec ruby main.rb
正在取得檔案路徑...成功
正在取得 META-INF/container.xml.../Users/yanxiangbo/Downloads/readmoo-dl-master/lib/readmoo_dl/downloader.rb:108:in `full_path': undefined method `+' for nil:NilClass (NoMethodError)
	from /Users/yanxiangbo/Downloads/readmoo-dl-master/lib/readmoo_dl/downloader.rb:49:in `fetch_container_file'
	from /Users/yanxiangbo/Downloads/readmoo-dl-master/lib/readmoo_dl/downloader.rb:25:in `block in download'
	from /Users/yanxiangbo/Downloads/readmoo-dl-master/lib/readmoo_dl/downloader.rb:38:in `job'
	from /Users/yanxiangbo/Downloads/readmoo-dl-master/lib/readmoo_dl/downloader.rb:25:in `download'
	from main.rb:19:in `<main>'

```
https://new-read.readmoo.com/mooreader/210258068000101

**Comment by NomadThanatos** [comment]
@Ramzh @PeepYXB I believe this should be another issue, I test with the download with https://readmoo.com/book/210088659000101, it still works well. Let me try to purchase one the book to see what happened, and if this is not related to the original issue, I will create another issue to track this.

**Comment by NomadThanatos** [comment]
Closed as the improvement is done. https://github.com/NomadThanatos/readmoo-dl/pull/30
