### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by FSZJ** [NomadThanatos/readmoo-dl#17]
```
正在取得檔案路徑.../Library/Ruby/Gems/2.6.0/gems/http-5.0.4/lib/http/timeout/null.rb:21:in `initialize': failed to connect: No route to host - connect(2) for "reader.readmoo.com" port 443 (HTTP::ConnectionError)
	from /Library/Ruby/Gems/2.6.0/gems/http-5.0.4/lib/http/timeout/null.rb:21:in `open'
	from /Library/Ruby/Gems/2.6.0/gems/http-5.0.4/lib/http/timeout/null.rb:21:in `connect'
	from /Library/Ruby/Gems/2.6.0/gems/http-5.0.4/lib/http/connection.rb:42:in `initialize'
	from /Library/Ruby/Gems/2.6.0/gems/http-5.0.4/lib/http/client.rb:70:in `new'
	from /Library/Ruby/Gems/2.6.0/gems/http-5.0.4/lib/http/client.rb:70:in `perform'
	from /Library/Ruby/Gems/2.6.0/gems/http-5.0.4/lib/http/client.rb:31:in `request'
	from /Library/Ruby/Gems/2.6.0/gems/http-5.0.4/lib/http/chainable.rb:20:in `get'
	from /Users/chrifs/Desktop/readmoo-dl-master/lib/readmoo_dl/API.rb:11:in `fetch'
	from /Users/chrifs/Desktop/readmoo-dl-master/lib/readmoo_dl/downloader.rb:43:in `fetch_base_file'
	from /Users/chrifs/Desktop/readmoo-dl-master/lib/readmoo_dl/downloader.rb:24:in `block in download'
	from /Users/chrifs/Desktop/readmoo-dl-master/lib/readmoo_dl/downloader.rb:38:in `job'
	from /Users/chrifs/Desktop/readmoo-dl-master/lib/readmoo_dl/downloader.rb:24:in `download'
	from main.rb:19:in `<main>'
/Library/Ruby/Gems/2.6.0/gems/http-5.0.4/lib/http/timeout/null.rb:21:in `initialize': No route to host - connect(2) for "reader.readmoo.com" port 443 (Errno::EHOSTUNREACH)
	from /Library/Ruby/Gems/2.6.0/gems/http-5.0.4/lib/http/timeout/null.rb:21:in `open'
	from /Library/Ruby/Gems/2.6.0/gems/http-5.0.4/lib/http/timeout/null.rb:21:in `connect'
	from /Library/Ruby/Gems/2.6.0/gems/http-5.0.4/lib/http/connection.rb:42:in `initialize'
	from /Library/Ruby/Gems/2.6.0/gems/http-5.0.4/lib/http/client.rb:70:in `new'
	from /Library/Ruby/Gems/2.6.0/gems/http-5.0.4/lib/http/client.rb:70:in `perform'
	from /Library/Ruby/Gems/2.6.0/gems/http-5.0.4/lib/http/client.rb:31:in `request'
	from /Library/Ruby/Gems/2.6.0/gems/http-5.0.4/lib/http/chainable.rb:20:in `get'
	from /Users/chrifs/Desktop/readmoo-dl-master/lib/readmoo_dl/API.rb:11:in `fetch'
	from /Users/chrifs/Desktop/readmoo-dl-master/lib/readmoo_dl/downloader.rb:43:in `fetch_base_file'
	from /Users/chrifs/Desktop/readmoo-dl-master/lib/readmoo_dl/downloader.rb:24:in `block in download'
	from /Users/chrifs/Desktop/readmoo-dl-master/lib/readmoo_dl/downloader.rb:38:in `job'
	from /Users/chrifs/Desktop/readmoo-dl-master/lib/readmoo_dl/downloader.rb:24:in `download'
	from main.rb:19:in `<main>'
```

**Comment by NomadThanatos** [comment]
`No route to host - connect(2) for "reader.readmoo.com" port 443 (HTTP::ConnectionError)`
Based on this I believe it is blocked by GFW, if not please check your internet.
