### ISSUE TITLE
下载问题

### ISSUE THREAD

**Issue by drsf864** [NomadThanatos/readmoo-dl#19]
无法下载，是网络问题吗？
just can't download anything. Is it a network problem, or is there something wrong with my settings?
```
正在取得檔案路徑...
DevTools listening on ws://127.0.0.1:2108/devtools/browser/8c4e3080-1939-4b61-94c4-6d1cabe39b9a
[32456:31700:1109/233306.544:ERROR:ssl_client_socket_impl.cc(975)] handshake failed; returned -1, SSL error code 1, net_error -100
[21000:30152:1109/233307.291:ERROR:cert_issuer_source_aia.cc(36)] Error parsing cert retrieved from AIA (as DER):
ERROR: Couldn't read tbsCertificate as SEQUENCE
ERROR: Failed parsing Certificate

[21000:30152:1109/233307.923:ERROR:cert_issuer_source_aia.cc(36)] Error parsing cert retrieved from AIA (as DER):
ERROR: Couldn't read tbsCertificate as SEQUENCE
ERROR: Failed parsing Certificate

[21000:30152:1109/233335.731:ERROR:cert_issuer_source_aia.cc(36)] Error parsing cert retrieved from AIA (as DER):
ERROR: Couldn't read tbsCertificate as SEQUENCE
ERROR: Failed parsing Certificate

[21000:30152:1109/233336.357:ERROR:cert_issuer_source_aia.cc(36)] Error parsing cert retrieved from AIA (as DER):
ERROR: Couldn't read tbsCertificate as SEQUENCE
ERROR: Failed parsing Certificate

[21000:30152:1109/233336.632:ERROR:cert_issuer_source_aia.cc(36)] Error parsing cert retrieved from AIA (as DER):
ERROR: Couldn't read tbsCertificate as SEQUENCE
ERROR: Failed parsing Certificate

E:/RUBY/Ruby32-x64/lib/ruby/gems/3.2.0/gems/http-5.0.4/lib/http/timeout/null.rb:21:in `initialize': failed to connect: Blocking operation timed out! (HTTP::ConnectionError)
        from E:/RUBY/Ruby32-x64/lib/ruby/gems/3.2.0/gems/http-5.0.4/lib/http/timeout/null.rb:21:in `open'
        from E:/RUBY/Ruby32-x64/lib/ruby/gems/3.2.0/gems/http-5.0.4/lib/http/timeout/null.rb:21:in `connect'
        from E:/RUBY/Ruby32-x64/lib/ruby/gems/3.2.0/gems/http-5.0.4/lib/http/connection.rb:42:in `initialize'
        from E:/RUBY/Ruby32-x64/lib/ruby/gems/3.2.0/gems/http-5.0.4/lib/http/client.rb:70:in `new'
        from E:/RUBY/Ruby32-x64/lib/ruby/gems/3.2.0/gems/http-5.0.4/lib/http/client.rb:70:in `perform'
        from E:/RUBY/Ruby32-x64/lib/ruby/gems/3.2.0/gems/http-5.0.4/lib/http/client.rb:31:in `request'
        from E:/RUBY/Ruby32-x64/lib/ruby/gems/3.2.0/gems/http-5.0.4/lib/http/chainable.rb:20:in `get'
        from E:/Download/readmoo-dl-master/lib/readmoo_dl/API.rb:11:in `fetch'
        from E:/Download/readmoo-dl-master/lib/readmoo_dl/downloader.rb:43:in `fetch_base_file'
        from E:/Download/readmoo-dl-master/lib/readmoo_dl/downloader.rb:24:in `block in download'
        from E:/Download/readmoo-dl-master/lib/readmoo_dl/downloader.rb:38:in `job'
        from E:/Download/readmoo-dl-master/lib/readmoo_dl/downloader.rb:24:in `download'
        from main.rb:19:in `<main>'
E:/RUBY/Ruby32-x64/lib/ruby/gems/3.2.0/gems/http-5.0.4/lib/http/timeout/null.rb:21:in `initialize': Blocking operation timed out! (IO::TimeoutError)
        from E:/RUBY/Ruby32-x64/lib/ruby/gems/3.2.0/gems/http-5.0.4/lib/http/timeout/null.rb:21:in `open'
        from E:/RUBY/Ruby32-x64/lib/ruby/gems/3.2.0/gems/http-5.0.4/lib/http/timeout/null.rb:21:in `connect'
        from E:/RUBY/Ruby32-x64/lib/ruby/gems/3.2.0/gems/http-5.0.4/lib/http/connection.rb:42:in `initialize'
        from E:/RUBY/Ruby32-x64/lib/ruby/gems/3.2.0/gems/http-5.0.4/lib/http/client.rb:70:in `new'
        from E:/RUBY/Ruby32-x64/lib/ruby/gems/3.2.0/gems/http-5.0.4/lib/http/client.rb:70:in `perform'
        from E:/RUBY/Ruby32-x64/lib/ruby/gems/3.2.0/gems/http-5.0.4/lib/http/client.rb:31:in `request'
        from E:/RUBY/Ruby32-x64/lib/ruby/gems/3.2.0/gems/http-5.0.4/lib/http/chainable.rb:20:in `get'
        from E:/Download/readmoo-dl-master/lib/readmoo_dl/API.rb:11:in `fetch'
        from E:/Download/readmoo-dl-master/lib/readmoo_dl/downloader.rb:43:in `fetch_base_file'
        from E:/Download/readmoo-dl-master/lib/readmoo_dl/downloader.rb:24:in `block in download'
        from E:/Download/readmoo-dl-master/lib/readmoo_dl/downloader.rb:38:in `job'
        from E:/Download/readmoo-dl-master/lib/readmoo_dl/downloader.rb:24:in `download'
        from main.rb:19:in `<main>'
```

**Comment by drsf864** [comment]
the book is
https://readmoo.com/book/210205204000101

**Comment by NomadThanatos** [comment]
Yeah I think so, even I do not login I would get some logs like this.
Please make sure that you have bypassed GFW.
```
[Nomad@GameBox readmoo-dl]$ bundle exec ruby main.rb
正在取得檔案路徑...成功
正在取得 META-INF/container.xml.../home/Nomad/readmoo-dl/lib/readmoo_dl/downloader.rb:108:in `full_path': undefined method `+' for nil:NilClass (NoMethodError)
        from /home/Nomad/readmoo-dl/lib/readmoo_dl/downloader.rb:49:in `fetch_container_file'
        from /home/Nomad/readmoo-dl/lib/readmoo_dl/downloader.rb:25:in `block in download'
        from /home/Nomad/readmoo-dl/lib/readmoo_dl/downloader.rb:38:in `job'
        from /home/Nomad/readmoo-dl/lib/readmoo_dl/downloader.rb:25:in `download'
        from main.rb:19:in `<main>'
```

**Comment by strange3374777** [comment]
can u add my telegram  @abc01234567897  i can pay you Money for do something

or we chat id   (houyee94)

or gmail  strange33747@gmail.com

**Comment by NomadThanatos** [comment]
@strange3374777 Hi could you please create another feature request issue, in English or Chinese are both fine to me, if I think this is a good add-on I will do it for free, recently I rarely use this program since most books I am interested are only sold in Taiwan, makes me wasting of lot of time for paying them money.

**Comment by strange3374777** [comment]
isn't that you can download for fee?

Yixiao Wen ***@***.***> 于 2024年5月16日周四 上午6:24写道：

**Comment by strange3374777** [comment]
i can download the book from hyread if u want can  telegram
me @abc01234567897

or wechat  houyee94

Lorry Low ***@***.***> 于 2024年5月16日周四 上午8:29写道：
