### ISSUE TITLE
bundle install 報錯，有許多extension不存在或無法取得的樣子

### ISSUE THREAD

**Issue by pelim95** [NomadThanatos/readmoo-dl#27]
你好，我下載了ZIP檔案，在解壓縮之後的 readmoo-dl-master\readmoo-dl-master 目錄下進行 bundle install 的時候，報了以下錯誤：

```bash
Fetching gem metadata from https://rubygems.org/.......
Using rake 13.0.6
Using bundler 2.3.12
Using public_suffix 4.0.7
Using childprocess 4.1.0
Using http-form_data 2.3.0
Using mini_portile2 2.8.5
Using racc 1.7.3
Fetching byebug 11.1.3
Using rexml 3.2.5
Fetching unf_ext 0.0.8.1
Fetching ffi 1.15.5
Using rubyzip 2.3.2
Using addressable 2.8.0
Using nokogiri 1.16.2 (x64-mingw-ucrt)
Using selenium-webdriver 4.1.0
Using webdrivers 5.3.1
Installing byebug 11.1.3 with native extensions
Installing unf_ext 0.0.8.1 with native extensions
Installing ffi 1.15.5 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
C:/tools/ruby33/lib/ruby/gems/3.3.0/gems/byebug-11.1.3/ext/byebug
C:/tools/ruby33/bin/ruby.exe extconf.rb
creating Makefile

current directory:
C:/tools/ruby33/lib/ruby/gems/3.3.0/gems/byebug-11.1.3/ext/byebug
make DESTDIR\= sitearchdir\=./.gem.20240807-13256-n9oe27
sitelibdir\=./.gem.20240807-13256-n9oe27 clean
current directory:
C:/tools/ruby33/lib/ruby/gems/3.3.0/gems/byebug-11.1.3/ext/byebug
make DESTDIR\= sitearchdir\=./.gem.20240807-13256-n9oe27
sitelibdir\=./.gem.20240807-13256-n9oe27
make failedNo such file or directory - make

Gem files will remain installed in
C:/tools/ruby33/lib/ruby/gems/3.3.0/gems/byebug-11.1.3 for inspection.
Results logged to
C:/tools/ruby33/lib/ruby/gems/3.3.0/extensions/x64-mingw-ucrt/3.3.0/byebug-11.1.3/gem_make.out

  C:/tools/ruby33/lib/ruby/3.3.0/rubygems/ext/builder.rb:102:in `rescue in run'
  C:/tools/ruby33/lib/ruby/3.3.0/rubygems/ext/builder.rb:90:in `run'
  C:/tools/ruby33/lib/ruby/3.3.0/rubygems/ext/builder.rb:51:in `block in make'
  C:/tools/ruby33/lib/ruby/3.3.0/rubygems/ext/builder.rb:43:in `each'
  C:/tools/ruby33/lib/ruby/3.3.0/rubygems/ext/builder.rb:43:in `make'
  C:/tools/ruby33/lib/ruby/3.3.0/rubygems/ext/ext_conf_builder.rb:42:in `build'
C:/tools/ruby33/lib/ruby/3.3.0/rubygems/ext/builder.rb:193:in
`build_extension'
C:/tools/ruby33/lib/ruby/3.3.0/rubygems/ext/builder.rb:227:in `block in
build_extensions'
  C:/tools/ruby33/lib/ruby/3.3.0/rubygems/ext/builder.rb:224:in `each'
C:/tools/ruby33/lib/ruby/3.3.0/rubygems/ext/builder.rb:224:in
`build_extensions'
  C:/tools/ruby33/lib/ruby/3.3.0/rubygems/installer.rb:852:in `build_extensions'
C:/tools/ruby33/lib/ruby/gems/3.3.0/gems/bundler-2.3.12/lib/bundler/rubygems_gem_installer.rb:71:in
`build_extensions'
C:/tools/ruby33/lib/ruby/gems/3.3.0/gems/bundler-2.3.12/lib/bundler/rubygems_gem_installer.rb:28:in
`install'
C:/tools/ruby33/lib/ruby/gems/3.3.0/gems/bundler-2.3.12/lib/bundler/source/rubygems.rb:204:in
`install'
C:/tools/ruby33/lib/ruby/gems/3.3.0/gems/bundler-2.3.12/lib/bundler/installer/gem_installer.rb:54:in
`install'
C:/tools/ruby33/lib/ruby/gems/3.3.0/gems/bundler-2.3.12/lib/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
C:/tools/ruby33/lib/ruby/gems/3.3.0/gems/bundler-2.3.12/lib/bundler/installer/parallel_installer.rb:186:in
`do_install'
C:/tools/ruby33/lib/ruby/gems/3.3.0/gems/bundler-2.3.12/lib/bundler/installer/parallel_installer.rb:177:in
`block in worker_pool'
C:/tools/ruby33/lib/ruby/gems/3.3.0/gems/bundler-2.3.12/lib/bundler/worker.rb:62:in
`apply_func'
C:/tools/ruby33/lib/ruby/gems/3.3.0/gems/bundler-2.3.12/lib/bundler/worker.rb:57:in
`block in process_queue'
  <internal:kernel>:187:in `loop'
C:/tools/ruby33/lib/ruby/gems/3.3.0/gems/bundler-2.3.12/lib/bundler/worker.rb:54:in
`process_queue'
C:/tools/ruby33/lib/ruby/gems/3.3.0/gems/bundler-2.3.12/lib/bundler/worker.rb:91:in
`block (2 levels) in create_threads'

An error occurred while installing byebug (11.1.3), and Bundler cannot continue.

In Gemfile:
  byebug


Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
C:/tools/ruby33/lib/ruby/gems/3.3.0/gems/unf_ext-0.0.8.1/ext/unf_ext
C:/tools/ruby33/bin/ruby.exe extconf.rb
checking for -lstdc++... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include=${opt-dir}/include
        --without-opt-include
        --with-opt-lib=${opt-dir}/lib
        --without-opt-lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/tools/ruby33/bin/$(RUBY_BASE_NAME)
        --with-static-libstdc++
        --without-static-libstdc++
        --with-stdc++-dir
        --without-stdc++-dir
        --with-stdc++-include=${stdc++-dir}/include
        --without-stdc++-include
        --with-stdc++-lib=${stdc++-dir}/lib
        --without-stdc++-lib
        --with-stdc++lib
        --without-stdc++lib
C:/tools/ruby33/lib/ruby/3.3.0/mkmf.rb:480:in `try_do': The compiler failed to
generate an executable file. (RuntimeError)
You have to install development tools first.

        from C:/tools/ruby33/lib/ruby/3.3.0/mkmf.rb:573:in `try_link0'
        from C:/tools/ruby33/lib/ruby/3.3.0/mkmf.rb:591:in `try_link'
        from C:/tools/ruby33/lib/ruby/3.3.0/mkmf.rb:809:in `try_func'
        from C:/tools/ruby33/lib/ruby/3.3.0/mkmf.rb:1056:in `block in have_library'
        from C:/tools/ruby33/lib/ruby/3.3.0/mkmf.rb:983:in `block in checking_for'
from C:/tools/ruby33/lib/ruby/3.3.0/mkmf.rb:344:in `block (2 levels) in
postpone'
        from C:/tools/ruby33/lib/ruby/3.3.0/mkmf.rb:314:in `open'
        from C:/tools/ruby33/lib/ruby/3.3.0/mkmf.rb:344:in `block in postpone'
        from C:/tools/ruby33/lib/ruby/3.3.0/mkmf.rb:314:in `open'
        from C:/tools/ruby33/lib/ruby/3.3.0/mkmf.rb:340:in `postpone'
        from C:/tools/ruby33/lib/ruby/3.3.0/mkmf.rb:982:in `checking_for'
        from C:/tools/ruby33/lib/ruby/3.3.0/mkmf.rb:1051:in `have_library'
        from extconf.rb:6:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can
be found here:

C:/tools/ruby33/lib/ruby/gems/3.3.0/extensions/x64-mingw-ucrt/3.3.0/unf_ext-0.0.8.1/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in
C:/tools/ruby33/lib/ruby/gems/3.3.0/gems/unf_ext-0.0.8.1 for inspection.
Results logged to
C:/tools/ruby33/lib/ruby/gems/3.3.0/extensions/x64-mingw-ucrt/3.3.0/unf_ext-0.0.8.1/gem_make.out

  C:/tools/ruby33/lib/ruby/3.3.0/rubygems/ext/builder.rb:125:in `run'
  C:/tools/ruby33/lib/ruby/3.3.0/rubygems/ext/ext_conf_builder.rb:28:in `build'
C:/tools/ruby33/lib/ruby/3.3.0/rubygems/ext/builder.rb:193:in
`build_extension'
C:/tools/ruby33/lib/ruby/3.3.0/rubygems/ext/builder.rb:227:in `block in
build_extensions'
  C:/tools/ruby33/lib/ruby/3.3.0/rubygems/ext/builder.rb:224:in `each'
C:/tools/ruby33/lib/ruby/3.3.0/rubygems/ext/builder.rb:224:in
`build_extensions'
  C:/tools/ruby33/lib/ruby/3.3.0/rubygems/installer.rb:852:in `build_extensions'
C:/tools/ruby33/lib/ruby/gems/3.3.0/gems/bundler-2.3.12/lib/bundler/rubygems_gem_installer.rb:71:in
`build_extensions'
C:/tools/ruby33/lib/ruby/gems/3.3.0/gems/bundler-2.3.12/lib/bundler/rubygems_gem_installer.rb:28:in
`install'
C:/tools/ruby33/lib/ruby/gems/3.3.0/gems/bundler-2.3.12/lib/bundler/source/rubygems.rb:204:in
`install'
C:/tools/ruby33/lib/ruby/gems/3.3.0/gems/bundler-2.3.12/lib/bundler/installer/gem_installer.rb:54:in
`install'
C:/tools/ruby33/lib/ruby/gems/3.3.0/gems/bundler-2.3.12/lib/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
C:/tools/ruby33/lib/ruby/gems/3.3.0/gems/bundler-2.3.12/lib/bundler/installer/parallel_installer.rb:186:in
`do_install'
C:/tools/ruby33/lib/ruby/gems/3.3.0/gems/bundler-2.3.12/lib/bundler/installer/parallel_installer.rb:177:in
`block in worker_pool'
C:/tools/ruby33/lib/ruby/gems/3.3.0/gems/bundler-2.3.12/lib/bundler/worker.rb:62:in
`apply_func'
C:/tools/ruby33/lib/ruby/gems/3.3.0/gems/bundler-2.3.12/lib/bundler/worker.rb:57:in
`block in process_queue'
  <internal:kernel>:187:in `loop'
C:/tools/ruby33/lib/ruby/gems/3.3.0/gems/bundler-2.3.12/lib/bundler/worker.rb:54:in
`process_queue'
C:/tools/ruby33/lib/ruby/gems/3.3.0/gems/bundler-2.3.12/lib/bundler/worker.rb:91:in
`block (2 levels) in create_threads'

An error occurred while installing unf_ext (0.0.8.1), and Bundler cannot
continue.

In Gemfile:
  http was resolved to 5.0.4, which depends on
    http-cookie was resolved to 1.0.4, which depends on
      domain_name was resolved to 0.5.20190701, which depends on
        unf was resolved to 0.1.4, which depends on
          unf_ext
```

想請問看看如何解決呢？

**Comment by williamzheng0711** [comment]
I encountered a similar problem as yours actually, and I am using Apple M1. I noticed in your response there is:  
```
Installing ffi 1.15.5 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
```

And my work-around is to run 
`sudo arch -arm64 gem install ffi`
Before running the "bundle install" command. Hope this may help.
